Templated components - TemplatedNavBar + @key (net8 BWA)
dotnet/blazor-samples pull request #266
Opened 2024-04-18 00:36 UTC by hakenr

https://github.com/dotnet/AspNetCore.Docs/issues/32229

@guardrex Could you please review the proposed samples? If they meet your approval, I'll replicate them across all versions and submit a pull request to the AspNetCore.Docs repo with the related text updates.

2024-04-18 00:39 UTC, guardrex commented
Sure thing ... first thing the morning. It's late here ... 8:40pm. I've been up since 4am, and I need some 🛌😴💤.

2024-04-18 08:13 UTC, hakenr commented
@guardrex To recap the intent:
1. For the basic explanation (current _Templated Components_ text), in `Pets1.razor` through `Pets4.razor`, I've replaced the `TableTemplate.razor` example with `TemplatedNavBar.razor`. Most of the existing text will remain unchanged.
2. I plan to add a new section describing and demonstrating the `@key` directive (with minimal text, mostly cross-linking to the existing discussion on keying). This new section will utilize the modified `TableTemplate.razor` and the new `Pets5.razor` to demonstrate this aspect.

The existing text and the new section will be interconnected, so at the end of the current section, I will add something like, "The example presented above assumes that the `Items` collection does not change after the initial render, or that there is no need to maintain the state of the components/elements used in `ItemTemplate` in case of changes. For templated components where such assumptions cannot be made, see the following section..."

2024-04-18 16:20 UTC, guardrex requested changes
Going great ... this is a fantastic set of updates!

2024-04-18 16:20 UTC, guardrex commented on 8.0/BlazorSample_BlazorWebApp/Components/Pages/Pets1.razor
> +        <NavLink href="@("/pets-" + pet.PetId)" class="nav-link">@pet.Name</NavLink>
Doesn't this kind'a 💥 break because we have `/pet-1`, `/pet-2`, ... component examples in the sample app that aren't really loading data for a given pet?

It seems like this should be a different URL not based on `/pet` ... use something like  `/pet-detail` that we know doesn't go anywhere. Also, it's too bad if the link doesn't do anything because I do like fully-working examples ... well ... silly examples that just don't break 🙈. Should there be a component to land on and show the pet id?

Let me rattle off an idea here ...

```suggestion
        <NavLink href="@($"/pet-detail/{pet.PetId}?ReturnUrl=%2Fpets-1")" class="nav-link">@pet.Name</NavLink>
```

Adding in something like ...

`PetDetail.razor`:

```razor
@page "/pet-detail/{id:int}"

<PageTitle>Pet Detail</PageTitle>

<h1>Pet Detail Record</h1>

<p>Pet ID: @Id</p>

<p><a href="@ReturnUrl">Return</a></p>

@code {
    [Parameter]
    public int Id { get; set; }

    [SupplyParameterFromQuery]
    public string? ReturnUrl { get; set; }
}
```

I realize that this doesn't matter for the article. The article doesn't need to show that, but it would be cool if the sample app included it to not break a user while playing with these examples.

Just an idea ... feel free to push back on it or consider just making the `href` be a dead link and not to `/pet-`.

2024-04-18 16:20 UTC, guardrex commented on 8.0/BlazorSample_BlazorWebApp/Components/Pages/Pets5.razor
> +        new Pet { PetId = 7, Name = "K-9" }
1-2-3 numbering?

```suggestion
        new Pet { PetId = 1, Name = "Mr. Bigglesworth" },
        new Pet { PetId = 2, Name = "Salem Saberhagen" },
        new Pet { PetId = 3, Name = "K-9" }
```

2024-04-18 17:10 UTC, hakenr commented on 8.0/BlazorSample_BlazorWebApp/Components/Pages/Pets1.razor
> +        <NavLink href="@("/pets-" + pet.PetId)" class="nav-link">@pet.Name</NavLink>
The original setup included a subtle feature where the `<NavLink />` component automatically adds an `.active` class to the rendered nav-link item when the current URL matches the link, subtly highlighting it. Typically, the entire nav-bar is placed in the page header via a layout component. In my initial setup, the `PetsN.razor` pages were essentially different versions of the `PetDetail.razor` page.

However, it's true that placing the nav-bar directly on individual pages to showcase various versions can make the whole thing harder to understand.

One idea is to shift the focus of the demos from pets to the more generic purpose of nav-bars "navigation between pages." I'm unsure if this change clarifies or complicates the demonstration.

`NavBarDemo{N}.razor`
```razor
@page "/navbar-demo-1"

<PageTitle>NavBar Demo 1 - Component-level Context</PageTitle>

<h1>NavBar Demo 1 - Component-level Context</h1>

<TemplatedNavBar Items="pages" Context="page">
    <StartContent>
        <a href="/" class="navbar-brand">Demos</a>
    </StartContent>
    <ItemTemplate>
        <NavLink href="@page.Url" class="nav-link">@page.Name</NavLink>
    </ItemTemplate>
</TemplatedNavBar>

@code {
    private List<DemoPage> pages = new()
    {
        new DemoPage { Url = "/navbar-demo-1", Name = "Component-level Context" },
        new DemoPage { Url = "/navbar-demo-2", Name = "Parameter-level Context" },
        new DemoPage { Url = "/navbar-demo-3", Name = "Original Context" },
        new DemoPage { Url = "/navbar-demo-4", Name = "Type Parameter" }
    };

    private class DemoPage
    {
        public string Url { get; set; }
        public string? Name { get; set; }
    }
}
```

If this idea doesn't resonate, we can proceed with the changes you proposed.

2024-04-18 17:37 UTC, guardrex commented on 8.0/BlazorSample_BlazorWebApp/Components/Pages/Pets1.razor
> +        <NavLink href="@("/pets-" + pet.PetId)" class="nav-link">@pet.Name</NavLink>
Well ... yeah ... but we'd be getting pretty far away from just demonstrating a base case for templates taking all of that into account. We need a whole new article :smile: ... ***The amazing things you can do with nav bars in Blazor*** 😆

The original pets demos in the live article today could just drop the ID parts ... replace them with another property ... so that they don't hint at a need to key anything. They'd just be demos of static content rendering with templates. The keying concept for templates would be later in the article with the new section/example.

This nav bar approach is fine, too, as a replacement. I just want to keep the introductory content focus on templates and not keying or nav bar implementation or anything else.

Again, I'm not pitching that the article needs to show and explain the pet detail part of this. Devs probably just need coverage on the template aspect ... the pets components and the template. The pet detail piece would only be here in the sample app to prevent these components from breaking 💥 as a demo when the sample app is run.

2024-04-19 10:34 UTC, guardrex requested changes
Fantastic and a lot of work!

This demonstrates my emerging concern for the future about sample app code and article examples. It's getting to be a giant PAIN 😩 to make a set of updates with sample apps stretching out over several years. Just think how terrible something like this will be at .NET 15 ... or .NET 20! It's going to become difficult to perform whole topic overhauls with a lot of sample code changes using the current versioning. I've begged management to give us *Version-by-File* versioning for docs, but they've basically refused.

Anyway ... I'm going to batch these suggestions on a commit in a minute, and then I might have one more ❓ about the updates after that. *Stand-by ............................*

2024-04-19 10:34 UTC, guardrex commented on 3.1/BlazorSample_Server/Pages/templated-components/Pets4.razor
> +            class="nav-link">@pet.Name</NavLink>
```suggestion
        <NavLink href="@($"/pet-detail/{pet.PetId}")" class="nav-link">
            @pet.Name
        </NavLink>
```

2024-04-19 10:34 UTC, guardrex commented on 3.1/BlazorSample_Server/Pages/templated-components/Pets5.razor
> +        // insert new pet every 3 seconds
```suggestion
        // Insert new pet every 3 seconds
```

2024-04-19 10:34 UTC, guardrex commented on 3.1/BlazorSample_WebAssembly/Pages/templated-components/Pets1.razor
> +            class="nav-link">@pet.Name</NavLink>
```suggestion
        <NavLink href="@($"/pet-detail/{pet.PetId}")" class="nav-link">
            @pet.Name
        </NavLink>
```

2024-04-19 10:34 UTC, guardrex commented on 3.1/BlazorSample_WebAssembly/Pages/templated-components/Pets2.razor
> +            class="nav-link">@pet.Name</NavLink>
```suggestion
        <NavLink href="@($"/pet-detail/{pet.PetId}")" class="nav-link">
            @pet.Name
        </NavLink>
```

2024-04-19 10:34 UTC, guardrex commented on 3.1/BlazorSample_WebAssembly/Pages/templated-components/Pets3.razor
> +            class="nav-link">@context.Name</NavLink>
```suggestion
        <NavLink href="@($"/pet-detail/{context.PetId}")" class="nav-link">
            @context.Name
        </NavLink>
```

2024-04-19 10:34 UTC, guardrex commented on 3.1/BlazorSample_WebAssembly/Pages/templated-components/Pets4.razor
> +            class="nav-link">@pet.Name</NavLink>
```suggestion
        <NavLink href="@($"/pet-detail/{pet.PetId}")" class="nav-link">
            @pet.Name
        </NavLink>
```

2024-04-19 10:34 UTC, guardrex commented on 3.1/BlazorSample_WebAssembly/Pages/templated-components/Pets5.razor
> +        // insert new pet every 3 seconds
```suggestion
        // Insert new pet every 3 seconds
```

2024-04-19 10:34 UTC, guardrex commented on 5.0/BlazorSample_Server/Pages/templated-components/Pets1.razor
> +            class="nav-link">@pet.Name</NavLink>
```suggestion
        <NavLink href="@($"/pet-detail/{pet.PetId}")" class="nav-link">
            @pet.Name
        </NavLink>
```

2024-04-19 10:34 UTC, guardrex commented on 5.0/BlazorSample_Server/Pages/templated-components/Pets2.razor
> +            class="nav-link">@pet.Name</NavLink>
```suggestion
        <NavLink href="@($"/pet-detail/{pet.PetId}")" class="nav-link">
            @pet.Name
        </NavLink>
```

2024-04-19 10:34 UTC, guardrex commented on 5.0/BlazorSample_Server/Pages/templated-components/Pets3.razor
> +            class="nav-link">@context.Name</NavLink>
```suggestion
        <NavLink href="@($"/pet-detail/{context.PetId}")" class="nav-link">
            @context.Name
        </NavLink>
```

2024-04-19 10:34 UTC, guardrex commented on 5.0/BlazorSample_Server/Pages/templated-components/Pets4.razor
> +            class="nav-link">@pet.Name</NavLink>
```suggestion
        <NavLink href="@($"/pet-detail/{pet.PetId}")" class="nav-link">
            @pet.Name
        </NavLink>
```

2024-04-19 10:34 UTC, guardrex commented on 5.0/BlazorSample_Server/Pages/templated-components/Pets5.razor
> +        // insert new pet every 3 seconds
```suggestion
        // Insert new pet every 3 seconds
```

2024-04-19 10:34 UTC, guardrex commented on 5.0/BlazorSample_WebAssembly/Pages/templated-components/Pets5.razor
> +        // insert new pet every 3 seconds
```suggestion
        // Insert new pet every 3 seconds
```

2024-04-19 10:34 UTC, guardrex commented on 6.0/BlazorSample_Server/Pages/templated-components/Pets1.razor
> +            class="nav-link">@pet.Name</NavLink>
```suggestion
        <NavLink href="@($"/pet-detail/{pet.PetId}")" class="nav-link">
            @pet.Name
        </NavLink>
```

2024-04-19 10:34 UTC, guardrex commented on 6.0/BlazorSample_Server/Pages/templated-components/Pets2.razor
> +            class="nav-link">@pet.Name</NavLink>
```suggestion
        <NavLink href="@($"/pet-detail/{pet.PetId}")" class="nav-link">
            @pet.Name
        </NavLink>
```

2024-04-19 10:34 UTC, guardrex commented on 6.0/BlazorSample_Server/Pages/templated-components/Pets3.razor
> +            class="nav-link">@context.Name</NavLink>
```suggestion
        <NavLink href="@($"/pet-detail/{context.PetId}")" class="nav-link">
            @context.Name
        </NavLink>
```

2024-04-19 10:34 UTC, guardrex commented on 6.0/BlazorSample_Server/Pages/templated-components/Pets4.razor
> +            class="nav-link">@pet.Name</NavLink>
```suggestion
        <NavLink href="@($"/pet-detail/{pet.PetId}")" class="nav-link">
            @pet.Name
        </NavLink>
```

2024-04-19 10:34 UTC, guardrex commented on 6.0/BlazorSample_Server/Pages/templated-components/Pets5.razor
> +        // insert new pet every 3 seconds
```suggestion
        // Insert new pet every 3 seconds
```

2024-04-19 10:34 UTC, guardrex commented on 6.0/BlazorSample_WebAssembly/Pages/templated-components/Pets1.razor
> +            class="nav-link">@pet.Name</NavLink>
```suggestion
        <NavLink href="@($"/pet-detail/{pet.PetId}")" class="nav-link">
            @pet.Name
        </NavLink>
```

2024-04-19 10:34 UTC, guardrex commented on 6.0/BlazorSample_WebAssembly/Pages/templated-components/Pets2.razor
> +            class="nav-link">@pet.Name</NavLink>
```suggestion
        <NavLink href="@($"/pet-detail/{pet.PetId}")" class="nav-link">
            @pet.Name
        </NavLink>
```

2024-04-19 10:34 UTC, guardrex commented on 6.0/BlazorSample_WebAssembly/Pages/templated-components/Pets3.razor
> +            class="nav-link">@context.Name</NavLink>
```suggestion
        <NavLink href="@($"/pet-detail/{context.PetId}")" class="nav-link">
            @context.Name
        </NavLink>
```

2024-04-19 10:34 UTC, guardrex commented on 6.0/BlazorSample_WebAssembly/Pages/templated-components/Pets4.razor
> +            class="nav-link">@pet.Name</NavLink>
```suggestion
        <NavLink href="@($"/pet-detail/{pet.PetId}")" class="nav-link">
            @pet.Name
        </NavLink>
```

2024-04-19 10:34 UTC, guardrex commented on 6.0/BlazorSample_WebAssembly/Pages/templated-components/Pets5.razor
> +        // insert new pet every 3 seconds
```suggestion
        // Insert new pet every 3 seconds
```

2024-04-19 10:34 UTC, guardrex commented on 7.0/BlazorSample_Server/Pages/templated-components/Pets1.razor
> +            class="nav-link">@pet.Name</NavLink>
My return URL idea makes the line a little too long. Let's just go for it in this case. Most of the time, I stick to <=85 characters, but all of us at times will break a rule because it doesn't compose code well. I think in this case for just a few characters that it's better to go over the limit just a bit.

```suggestion
        <NavLink href="@($"/pet-detail/{pet.PetId}?ReturnUrl=%2Fpets-1")" class="nav-link">
            @pet.Name
        </NavLink>
```

2024-04-19 10:34 UTC, guardrex commented on 7.0/BlazorSample_Server/Pages/templated-components/Pets2.razor
> +            class="nav-link">@pet.Name</NavLink>
```suggestion
        <NavLink href="@($"/pet-detail/{pet.PetId}?ReturnUrl=%2Fpets-2")" class="nav-link">
            @pet.Name
        </NavLink>
```

2024-04-19 10:34 UTC, guardrex commented on 7.0/BlazorSample_Server/Pages/templated-components/Pets3.razor
> +            class="nav-link">@context.Name</NavLink>
```suggestion
        <NavLink href="@($"/pet-detail/{context.PetId}?ReturnUrl=%2Fpets-3")" class="nav-link">
            @context.Name
        </NavLink>
```

2024-04-19 10:34 UTC, guardrex commented on 7.0/BlazorSample_Server/Pages/templated-components/Pets4.razor
> +            class="nav-link">@pet.Name</NavLink>
```suggestion
        <NavLink href="@($"/pet-detail/{pet.PetId}?ReturnUrl=%2Fpets-4")" class="nav-link">
            @pet.Name
        </NavLink>
```

2024-04-19 10:34 UTC, guardrex commented on 7.0/BlazorSample_Server/Pages/templated-components/Pets5.razor
> +        // insert new pet every 3 seconds
```suggestion
        // Insert new pet every 3 seconds
```

2024-04-19 10:34 UTC, guardrex commented on 7.0/BlazorSample_WebAssembly/Pages/templated-components/Pets1.razor
> +            class="nav-link">@pet.Name</NavLink>
```suggestion
        <NavLink href="@($"/pet-detail/{pet.PetId}?ReturnUrl=%2Fpets-1")" class="nav-link">
            @pet.Name
        </NavLink>
```

2024-04-19 10:34 UTC, guardrex commented on 7.0/BlazorSample_WebAssembly/Pages/templated-components/Pets2.razor
> +            class="nav-link">@pet.Name</NavLink>
```suggestion
        <NavLink href="@($"/pet-detail/{pet.PetId}?ReturnUrl=%2Fpets-2")" class="nav-link">
            @pet.Name
        </NavLink>
```

2024-04-19 10:34 UTC, guardrex commented on 7.0/BlazorSample_WebAssembly/Pages/templated-components/Pets3.razor
> +            class="nav-link">@context.Name</NavLink>
```suggestion
        <NavLink href="@($"/pet-detail/{context.PetId}?ReturnUrl=%2Fpets-3")" class="nav-link">
            @context.Name
        </NavLink>
```

2024-04-19 10:34 UTC, guardrex commented on 7.0/BlazorSample_WebAssembly/Pages/templated-components/Pets4.razor
> +            class="nav-link">@pet.Name</NavLink>
```suggestion
        <NavLink href="@($"/pet-detail/{pet.PetId}?ReturnUrl=%2Fpets-4")" class="nav-link">
            @pet.Name
        </NavLink>
```

2024-04-19 10:34 UTC, guardrex commented on 7.0/BlazorSample_WebAssembly/Pages/templated-components/Pets5.razor
> +        // insert new pet every 3 seconds
```suggestion
        // Insert new pet every 3 seconds
```

2024-04-19 10:34 UTC, guardrex commented on 8.0/BlazorSample_BlazorWebApp/Components/Pages/Pets1.razor
> +            class="nav-link">@pet.Name</NavLink>
```suggestion
        <NavLink href="@($"/pet-detail/{pet.PetId}?ReturnUrl=%2Fpets-1")" class="nav-link">
            @pet.Name
        </NavLink>
```

2024-04-19 10:34 UTC, guardrex commented on 8.0/BlazorSample_BlazorWebApp/Components/Pages/Pets2.razor
> +            class="nav-link">@pet.Name</NavLink>
```suggestion
        <NavLink href="@($"/pet-detail/{pet.PetId}?ReturnUrl=%2Fpets-2")" class="nav-link">
            @pet.Name
        </NavLink>
```

2024-04-19 10:34 UTC, guardrex commented on 8.0/BlazorSample_BlazorWebApp/Components/Pages/Pets3.razor
> +            class="nav-link">@context.Name</NavLink>
```suggestion
        <NavLink href="@($"/pet-detail/{context.PetId}?ReturnUrl=%2Fpets-3")" class="nav-link">
            @context.Name
        </NavLink>
```

2024-04-19 10:34 UTC, guardrex commented on 8.0/BlazorSample_BlazorWebApp/Components/Pages/Pets4.razor
> +            class="nav-link">@pet.Name</NavLink>
```suggestion
        <NavLink href="@($"/pet-detail/{pet.PetId}?ReturnUrl=%2Fpets-4")" class="nav-link">
            @pet.Name
        </NavLink>
```

2024-04-19 10:34 UTC, guardrex commented on 8.0/BlazorSample_BlazorWebApp/Components/Pages/Pets5.razor
> +        // insert new pet every 3 seconds
```suggestion
        // Insert new pet every 3 seconds
```

2024-04-19 10:34 UTC, guardrex commented on 8.0/BlazorSample_WebAssembly/Pages/Pets1.razor
> +            class="nav-link">@pet.Name</NavLink>
```suggestion
        <NavLink href="@($"/pet-detail/{pet.PetId}?ReturnUrl=%2Fpets-1")" class="nav-link">
            @pet.Name
        </NavLink>
```

2024-04-19 10:34 UTC, guardrex commented on 8.0/BlazorSample_WebAssembly/Pages/Pets2.razor
> +            class="nav-link">@pet.Name</NavLink>
```suggestion
        <NavLink href="@($"/pet-detail/{pet.PetId}?ReturnUrl=%2Fpets-2")" class="nav-link">
            @pet.Name
        </NavLink>
```

2024-04-19 10:34 UTC, guardrex commented on 8.0/BlazorSample_WebAssembly/Pages/Pets3.razor
> +            class="nav-link">@context.Name</NavLink>
```suggestion
        <NavLink href="@($"/pet-detail/{context.PetId}?ReturnUrl=%2Fpets-3")" class="nav-link">
            @context.Name
        </NavLink>
```

2024-04-19 10:34 UTC, guardrex commented on 8.0/BlazorSample_WebAssembly/Pages/Pets4.razor
> +            class="nav-link">@pet.Name</NavLink>
```suggestion
        <NavLink href="@($"/pet-detail/{pet.PetId}?ReturnUrl=%2Fpets-4")" class="nav-link">
            @pet.Name
        </NavLink>
```

2024-04-19 10:34 UTC, guardrex commented on 8.0/BlazorSample_WebAssembly/Pages/Pets5.razor
> +        // insert new pet every 3 seconds
```suggestion
        // Insert new pet every 3 seconds
```

2024-04-19 10:45 UTC, guardrex commented
Why the `OnAfterRenderAsync` piece? I don't see the value of doing that (*yet* 😄).

2024-04-19 10:52 UTC, guardrex commented
BTW on the line length ... ***Yes!*** I broke the rule on those return URL lines. They compose better if they're allowed to break the "rule" by a few characters. Most of the time, we all stick to the <=85 character rule. We all break that rule here and there if the code, markup in this case, doesn't compose well and only going over the limit by a handful of characters.

2024-04-19 10:54 UTC, hakenr commented
> Why the `OnAfterRenderAsync` piece? I don't see the value of doing that (_yet_ 😄).

For .NET 6 and earlier, demo apps have prerendering enabled. Using `OnParametersSetAsync()` for this purpose causes the prerendering process to delay until all cycles are complete, leading to a 30+ second wait for the server to generate the pre-rendered HTML. Since `OnAfterRenderAsync()` isn’t invoked during prerendering, it avoids this delay.

2024-04-19 10:57 UTC, hakenr commented
> This demonstrates my emerging concern for the future about sample app code and article examples. It's getting to be a giant PAIN 😩 to make a set of updates with sample apps stretching out over several years. Just think how terrible something like this will be at .NET 15 ... or .NET 20! It's going to become difficult to perform whole topic overhauls with a lot of sample code changes using the current versioning. I've begged management to give us Version-by-File versioning for docs, but they've basically refused.

Do we really need to maintain all the samples for .NET versions that are no longer supported, such as .NET 3.1 and .NET 5?

2024-04-19 11:08 UTC, guardrex commented
Yes, but my question is why do that at all? What purpose does adding the new (empty) pet records serve when demonstrating templating? That isn't how records would normally ever be added to a typical table use case, unless I'm missing something ... you have a lot more real world, hand-on, production Blazor experience than I have. If adding something makes sense, perhaps having a button in the component add one new new pet record with a correct ID and a real name.

> Do we really need to maintain all the samples for .NET versions that are no longer supported, such as .NET 3.1 and .NET 5?

Unfortunately, ***YES*** and no ...

No ... in the sense that the sample apps don't fall under Microsoft's rule for maintaining versioned content, so there is flexibility on what's in the sample apps.

Yes ... in the sense that the article itself must maintain versioned content ***forever!*** As it stands today unless they change their minds at some point, we must maintain 3.1 ***forever*** (etc.) forever.

I've begged them for *Version-by-File* for several years, where each version of the doc is a different file on the repo. I even almost had a working Version-by-File implementation, but I received about ZERO help from MS DocFX engineers and management to get it fully implemented. Actually, it was less than zero help really because all they did was make me mad as hell 😡 at the way they were giving me the run-around and being deliberately obtuse. Rick also tried to work with them a year or two later, and he had a similar experience.

When you think about how our single-file versioning system works in the articles, you can see that this whole versioning system is just going to get worse and worse as the years roll on. I'll take it up with Dan and Artak again at some point. I think what's going to have to happen is that Dan is going to have to directly discuss this with their upper management because they certainly don't care what a silly green dinosaur 🦖 thinks about it 😆.

Anyway ... Tell me more about why we need to be adding records ***at all*** to this ... or why it would be better that way over say having a single button just add a proper pet ... correct ID and a real name.

2024-04-19 11:21 UTC, hakenr commented
> Yes, but my question is why do that at all? What purpose does adding the new (empty) pet records serve when demonstrating templating? That isn't how records would normally ever be added to a typical table use case, unless I'm missing something ... you have a lot more real world, hands-on, production Blazor experience than I have. If adding something makes sense, perhaps having a button in the component to add one new pet record with a correct ID and a real name.

Actually, I'm replicating the demonstration used in https://learn.microsoft.com/en-us/aspnet/core/blazor/components/element-component-model-relationships?view=aspnetcore-8.0 (see `People.razor`).

In this demo, "Being focused" is the state we want to preserve for the `input` between roundtrips. We cannot use a button to add a new pet because "selecting" 😇 a button shifts the focus from the input to the button.

With `@key`:
![2024-04-19_13-18-25](https://github.com/dotnet/blazor-samples/assets/12828888/64de08b3-c665-49e6-b332-89a861b03af9)

Without `@key` in `TableTemplate.razor`:
![2024-04-19_13-20-14](https://github.com/dotnet/blazor-samples/assets/12828888/4cc00713-2f21-4a95-845d-75dfd5f88fc3)

Wish there was a way to add an animated GIF to the doc, ...

2024-04-19 11:25 UTC, hakenr commented
Should I try to come up with a more realistic demo that would demonstrate the need to preserve state between roundtrips? Maybe as a separate issue and PR, so as not to block completing this PR and to give us some time to think it over?

2024-04-19 11:25 UTC, guardrex commented
I see ... is there any way for the added records to have a proper ID and a real pet name? Could you add five records instead of ten, give them proper (non-zero, non-repeating) IDs and use five more ***movie*** (or TV show) pet names?

Also ... I haven't looked yet at the article updates ... but are you explaining what you just said over in the article ... are you walking the reader through doing what you just showed 👆 so that they can experience that with the component. If not, it would only take a short paragraph, right?

2024-04-19 11:26 UTC, guardrex commented
I like the demo a lot now that you've explained it. I just think the article should have a paragraph to explain that.

2024-04-19 11:34 UTC, hakenr commented
> I see ... is there any way for the added records to have a proper ID and a real pet name? Could you add five records instead of ten, give them proper (non-zero, non-repeating) IDs and use five more movie (or TV show) pet names?

Yes, but it will  make the sample code longer. These new items were means as new records, but the whole scenario is very simplified and not so real.

> Also ... I haven't looked yet at the article updates ... but are you explaining what you just said over in the article ... are you walking the reader through doing what you just showed 👆 so that they can experience that with the component. If not, it would only take a short paragraph, right?

Please review the text in the new section of the page and let me know if there's anything else I should include. As a non-native speaker, it's challenging for me, but I will strive to make the next update as good as possible.

> ... and perhaps add five real records ... perhaps go back to the five second delay ... I understand better now how the five second delay makes more sense.

OK.

2024-04-19 11:39 UTC, guardrex commented
True ... I admit it. Perhaps, the article will end up stating to the reader that the purpose is to demonstrate the concept and not meant to reflect how records are normally added.

The alternative might be to dump it anyway ... go back to my first thought about it ... 🔪 it out of here. Now that I see where you were going with it, I wonder if the article can just cross-link to *Retain element, component, and model relationships in ASP.NET Core Blazor* and tell the reader that this is why it's important to `@key`. This demo doesn't need to do it at all. Then, this really is shorter code to look at. The example over in the other article demonstrates the keying piece. Devs can take your word for it here as to the value of doing it here.

2024-04-19 12:17 UTC, hakenr commented
> Which answer were you 😕 by in my earlier post?

😁 The need to maintain all the legacy samples and the story behind the docs system. 😇

2024-04-19 12:21 UTC, guardrex commented
The workarounds are ugly ... for example, placing code back into the articles. Even then, changes in coding (e.g., NRTs) cause you to want to version code in the articles further. It's ugly all the way around. Version-by-File would solve most of the problems, but they aren't keen on helping me implement it.

Eventually, I'll discuss it with Dan and Artak again. It's costing MS 💰 ***MONEY*** 💰 now, and it's just going to cost more and more 💲💲💲💲 as the years roll on. At some point, I think MS docs are going to have to do something about it.

2024-04-19 12:29 UTC, hakenr commented
> The workarounds are ugly ... for example, placing code back into the articles. Even then, changes in coding (e.g., NRTs) cause you to want to version code in the articles further. It's ugly all the way around. Version-by-File would solve most of the problems, but they aren't keen on helping me implement it.
> 
> Eventually, I'll discuss it with Dan and Artak again. It's costing MS 💰 _**MONEY**_ 💰 now, and it's just going to cost more and more 💲💲💲💲 as the years roll on. At some point, I think MS docs are going to have to do something about it.

I think this will also cost Microsoft the willingness of contributors to participate in the samples. The copying between versions and downgrading implementations to exclude previously nonexistent features is a nightmare.

2024-04-19 12:36 UTC, guardrex commented
Totally agree! Thanks for mentioning that, and I'm going to remember it and cross-link to your remark (and show the amount of work it took here) when I chat with Dan and Artak about this.

It's a pain point for me, too. One might say, 'hey! hey! ... job security' ... no ... no ... I don't want to spend my short time on 🌍 mired in grunt work. Besides, I don't provide services to clients that way. I always look to save the client 💰. Even when the docs folks weren't going to help me with *Version-by-File*, I tried to implement it anyway on my own without their help. It's a bit of a game-changer on maintaining docs, and it should've been instituted many years ago IMO. Too bad they don't get it 😢.

2024-04-19 12:57 UTC, guardrex approved these changes
# 🎉 

Great idea. I know that doesn't really matter all that much (super NIT), but it's a little nicer than before.

2024-04-19 13:11 UTC, merged