modernize per analyzers
dotnet/blazor-samples pull request #341
Opened 2024-08-25 18:30 UTC by DickBaker

the existing .SLN raises Warnings/Messages and analyzers encourage modernizing changes.

This PR offers cleaner code, so I hope MS owners will accept these changes as-is
but **Allow edits by maintainers** checkbox set to allow tweaking

2024-08-25 18:38 UTC, DickBaker commented
sorry, my first commit only touched 1 file and rest stayed behind. Hopefully this 2nd attempt will work for all changed files.

2024-08-26 14:22 UTC, guardrex commented
Thanks @DickBaker ... You dropped the `var` keyword in favor of explicit types. We follow (most of) the ASP.NET Core framework coding guidelines, and the use of `var` with implicit types is a coding guideline that we follow here, even if the analyzer isn't happy about it 😄. Those lines must be reverted. After that, I'll get Jeremy in to take a look, as this is his sample app. Everything else looks *GrEaT* to me! 👍

BTW --- If reverting the `var` lines is too much of a chore, I'll take care of it.

2024-08-27 10:13 UTC, guardrex requested changes

2024-08-27 10:13 UTC, guardrex commented on 8.0/BlazorWebAppEFCore/DatabaseUtility.cs
> +        DbContextOptionsBuilder<ContactContext> builder = new DbContextOptionsBuilder<ContactContext>(options)
```suggestion
        var builder = new DbContextOptionsBuilder<ContactContext>(options)
```

2024-08-27 10:13 UTC, guardrex commented on 8.0/BlazorWebAppEFCore/DatabaseUtility.cs
> +        await using ContactContext context = new(builder.Options);
```suggestion
        using var context = new ContactContext(builder.Options);
```

2024-08-27 10:13 UTC, guardrex commented on 8.0/BlazorWebAppEFCore/Grid/GridQueryAdapter.cs
> +        List<Contact> collection = await FetchPageQuery(query)
```suggestion
        var collection = await FetchPageQuery(query)
```

2024-08-27 10:13 UTC, guardrex commented on 8.0/BlazorWebAppEFCore/Grid/GridQueryAdapter.cs
> +            Func<IQueryable<Contact>, IQueryable<Contact>> filter = _filterQueries[_controls.FilterColumn];
```suggestion
            var filter = _filterQueries[_controls.FilterColumn];
```

2024-08-27 10:13 UTC, guardrex commented on 8.0/BlazorWebAppEFCore/Grid/GridQueryAdapter.cs
> +        Expression<Func<Contact, string>> expression = _expressions[_controls.SortColumn];
```suggestion
        var expression = _expressions[_controls.SortColumn];
```

2024-08-27 10:13 UTC, guardrex commented on 8.0/BlazorWebAppEFCore/Program.cs
> +WebApplicationBuilder builder = WebApplication.CreateBuilder(args);
```suggestion
var builder = WebApplication.CreateBuilder(args);
```

2024-08-27 10:13 UTC, guardrex commented on 8.0/BlazorWebAppEFCore/Program.cs
> +WebApplication app = builder.Build();
```suggestion
var app = builder.Build();
```

2024-08-27 10:13 UTC, guardrex commented on 8.0/BlazorWebAppEFCore/Program.cs
> +await using AsyncServiceScope scope = app.Services.GetRequiredService<IServiceScopeFactory>().CreateAsyncScope();
```suggestion
await using var scope = app.Services.GetRequiredService<IServiceScopeFactory>().CreateAsyncScope();
```

2024-08-27 10:13 UTC, guardrex commented on 8.0/BlazorWebAppEFCore/Program.cs
> +DbContextOptions<ContactContext> options = scope.ServiceProvider.GetRequiredService<DbContextOptions<ContactContext>>();
```suggestion
var options = scope.ServiceProvider.GetRequiredService<DbContextOptions<ContactContext>>();
```

2024-08-27 13:57 UTC, DickBaker commented
**Luke**, thanks for doing the "var" dance to save me the effort. As part of my refactoring I had applied the "_Analyze and Code Cleanup_", "_Run Code Cleanup (profile 1)_" with my settings to apply ALL the .editorconfig particulars. My VS would have input the .editorconfig from the repo's primitive
https://github.com/dotnet/blazor-samples/blob/main/.editorconfig 17 lines
versus
https://github.com/dotnet/runtime/blob/main/.editorconfig 190 lines
https://github.com/dotnet/docs/blob/main/.editorconfig  210 lines
https://github.com/dotnet/aspnetcore 475 lines

Obviously the .editorconfig is there to herd devs into some standard pens,
so my [**strong**!] suggestion is that you cherry-pick the bits _you_ like, e.g.
csharp_style_var_for_built_in_types = true
csharp_style_var_when_type_is_apparent = true
csharp_style_var_elsewhere = false

but I don't dare to propose any more subjective electives: over to Jeremy/your team to argue the specifics!

2024-08-27 14:34 UTC, guardrex commented
`.editorconfig` was placed by Robert Haken with the basic settings. I've been busy, and it's a low priority. I opened #345 to work on it later, hopefully by EOY. Thanks for your remarks because it probably would've sat for much longer had you not said something.

2024-08-27 14:51 UTC, DickBaker commented
yup, I see MVP Robert Haken's commit back in Feb, and I reckon he was equally hesitant to tell you owners how to suck eggs (but nice to have European inputs), so best of luck for you/Jeremy rolling the dice for gory details (I will watch #341 from the touchlines). Maybe loop-in Robert anyway as prev contributor?

2024-09-04 16:56 UTC, guardrex commented
Jeremy looked it over and said (via email) that it looks good.

*Merging now!* 🎉 Thanks again!

2024-09-04 16:57 UTC, merged