MauiBlazorWeb for 9.0
dotnet/blazor-samples pull request #370
Opened 2024-10-14 15:23 UTC by guardrex

### MauiBlazorWeb 9.0 (second attempt 🙈😄) 

Based on the latest template with `InteractiveRenderSettings` added. After this is merged, I'll check the article to see if it requires updates to match the sample app changes.

I used the same local branch and didn't squash, so no worries on the old commits.

Seems to run well ...

![image](https://github.com/user-attachments/assets/f8836d19-fa2a-483b-9c23-b3efd6bd32a4)

2024-10-15 23:51 UTC, BethMassi requested changes
You need to import the InteractiveRenderSettings class in the Share project for this to work with per page/component.

2024-10-15 23:51 UTC, BethMassi commented on 9.0/MauiBlazorWeb/MauiBlazorWeb.Shared/_Imports.razor
> +@using static Microsoft.AspNetCore.Components.Web.RenderMode
```suggestion
@using static InteractiveRenderSettings
```

2024-10-16 11:26 UTC, guardrex commented on 9.0/MauiBlazorWeb/MauiBlazorWeb.Shared/_Imports.razor
> +@using static Microsoft.AspNetCore.Components.Web.RenderMode
`@using static InteractiveRenderSettings` is already on Line 9 of the file.

I'll remove Line 6.

2024-10-16 18:34 UTC, BethMassi approved these changes
Looks good, thank you!

2024-10-16 18:35 UTC, merged

2024-10-16 18:35 UTC, guardrex commented
I'll work on the article next and ping u on that PR when it goes up.